name: tofu-validate
description: Validate an OpenTofu configuration directory
author: Daniel Flook

inputs:
  path:
    description: The path to the OpenTofu module to validate
    required: false
    default: "."
  workspace:
    description: |
      OpenTofu workspace to use for the `terraform.workspace` value while validating. Note that for remote operations in a cloud backend, this is always `default`.

      Also used for discovering the OpenTofu version to use, if not otherwise specified. 
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: "default"
  backend_config:
    description: |
      List of OpenTofu backend config values, one per line.
      This is used for discovering the OpenTofu version to use, if not otherwise specified. 
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
      This is used for discovering the OpenTofu version to use, if not otherwise specified. 
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: ""

outputs:
  failure-reason:
    description: |
      When the job outcome is `failure` because the validation failed, this will be set to 'validate-failed'.
      If the job fails for any other reason this will not be set.
      This can be used with the Actions expression syntax to conditionally run a step when the validate fails.

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:7aef5fd3c9c6b005c5fe0a77b3065e5a2eeed4650993041a54c25013761237f7
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
